### PR TITLE
including events for use in event detail page tests

### PR DESCRIPTION
**Pull request by xavid**

### CODE REVIEW

**Comment by kljensen** [comment]
David, I took our `events` because we're also using this code on the [mgt656-website](https://git.yale.edu/mgt656/mgt656-website) where we don't have access to the models. I need the tests to stand alone w/o the models

**Comment by xavid** [comment]
Ahhh... Then the call to async.map(events.all... (currently around #L230) will have to be refactored out, as it currently throws error events not defined.

Even when it works, it has a bug because it attempts to loop through the events from id 0 to 3, but actual events in the model are [0, 1, 2, 4].

What would you think about killing async.map and hard-coding the events? They're hard-coded into the model as is.

**Comment by kljensen** [comment]
good catch

**Comment by kljensen** [comment]
Closed by bd1c3e58b55e0a1b41f4f9ec0e0963beb9bb90db

**Pull request closed without merging**
